# Generated by Django 6.1 on 2026-08-06 17:34

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.avatar_upload_path, validators=[profiles.models.validate_avatar_size, profiles.models.validate_avatar_type]),
        ),
    ]
