services:
  - type: web
    name: senproject
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DB_PATH
        value: /var/data/db.sqlite3
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: ALLOWED_HOSTS
        value: "senproject-ifo5.onrender.com,senproject.onrender.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"